# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"

def find_difference(s, t):
    
    s_dict = {}
    t_dict = {}
    
    for char in s:
        s_dict[char] = s_dict.get(char, 0) + 1
    
    for char in t:
        t_dict[char] = t_dict.get(char, 0) + 1

        if s_dict.get(char, 0) == 0 or t_dict.get(char, 0) > s_dict.get(char, 0):
            return char
    
s = "abcd"
t = "abcde"
print(find_difference(s, t))
